# Generated by Django 5.2.6 on 2025-09-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
