# Generated by Django 5.2.6 on 2025-10-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_registerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='session_id',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
