# Generated by Django 5.2.6 on 2025-10-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contactdetails_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdetails',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='full_name',
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
