# Generated by Django 5.2.6 on 2025-10-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_phone_number_contactdetails_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='screenshot',
            field=models.FileField(null=True, upload_to='screenshot'),
        ),
    ]
