# Generated by Django 5.2.6 on 2025-11-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contactdetails_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='screenshot'),
        ),
    ]
